# Generated by Django 3.1.2 on 2020-12-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(open('./database.sql', 'r').read())
    ]
