# Generated by Django 3.1.2 on 2020-12-22 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201222_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='isDone',
            new_name='is_done',
        ),
    ]
